name: medcode
description: A medical codes management application built with Flutter Clean Architecture.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2

  # Networking
  dio: ^5.4.0
  connectivity_plus: ^6.0.5

  # Local Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  # Routing
  go_router: ^13.0.0

  # File picking
  file_picker: ^8.0.3
  permission_handler: ^11.3.1
  path_provider: ^2.1.1
  share_plus: ^7.2.1

  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Utilities
  intl: ^0.19.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1

  # Testing
  bloc_test: ^9.1.5
  mockito: ^5.4.4
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/icons/logo.png
  min_sdk_android: 21




